version: "2.2"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka:2.11-1.1.1
    ports:
      - "9092:9092"
    links:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${HOST_IP}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "topic-test:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  #  nodejs:
  #    build:
  #      context: .
  #      dockerfile: Dockerfile
  #    depends_on:
  #      - es01
  #    image: nodejs
  #    container_name: nodejs
  #    env_file: .env
  #    ports:
  #      - "3000:3000"
  #    links:
  #      - es01
  #    volumes:
  #      - .:/home/node/app
  #      - node_modules:/home/node/app/node_modules
  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
volumes:
  data01:
    driver: local
  node_modules:
